Web/Controllers/FactureController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using GP.Data;
using GP.Domain.Entities;
//
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using GP.Service;
using System.Globalization;

namespace GP.Web.Controllers
{
    public class FactureController : Controller
    {
        // GET: FactureController
        private readonly IFactureService fctsrv;
        private readonly IClientService cltsrv;
        private readonly IProductService prdsrv;
        public FactureController(IFactureService _fctsrv, IClientService _cltsrv, IProductService _prdsrv)
        {
            fctsrv = _fctsrv;
            cltsrv = _cltsrv;
            prdsrv = _prdsrv;
        }
        public ActionResult Index()
        {
            return View(fctsrv.GetMany());
        }

        // GET: FactureController/Details/5
        public ActionResult Details(int? Productid, int? ClientId, DateTime Dateachat)
        {
            if (Productid == null)
            {
                return NotFound();
            }

            var facture = fctsrv.GetMany()
                .FirstOrDefault(m => m.ProductFk == Productid && m.ClientFk== ClientId && m.DateAchat == Dateachat);
            if (facture == null)
            {
                return NotFound();
            }

            return View(facture);
        }

        // GET: FactureController/Create
        public ActionResult Create()
        {
            ViewBag.ProductFk = new SelectList(prdsrv.GetMany(), "ProductId", "Name");
            ViewBag.ClientFk = new SelectList(cltsrv.GetMany(), "Cin", "Prenom");
            return View();
        }

        // POST: FactureController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Facture facture)
        {
            try
            {
                fctsrv.Add(facture);
                fctsrv.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: FactureController/Edit/5
        public ActionResult Edit(int? Productid, int? ClientId, DateTime Dateachat)
        {
            if ((Productid == null)|| (ClientId==null))
            {
                return NotFound();
            }

            var facture = fctsrv.GetMany()
                .FirstOrDefault(m => m.ProductFk == Productid && m.ClientFk == ClientId && m.DateAchat == Dateachat); 
            if (facture == null)
            {
                return NotFound();
            }
            //ViewBag.ProductFk = prdsrv.GetMany().Where(a => a.ProductId == Productid).FirstOrDefault().Name;
            //ViewBag.ClientFk = cltsrv.GetMany().Where(a => a.Cin == ClientId).FirstOrDefault().Prenom; 

            return View(facture);
        }

        // POST: FactureController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Facture facture)
        {

            try
            {
                Facture fct = fctsrv.GetMany().Where(f => f.ProductFk == facture.ProductFk && f.ClientFk == facture.ClientFk && f.DateAchat== facture.DateAchat)
                .FirstOrDefault();

                fct.Prix = facture.Prix;

                fctsrv.Update(fct);
                fctsrv.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {

                return View(facture);
            }
        }

        // GET: FactureController/Delete/5
        public ActionResult Delete(int? Productid, int? ClientId, DateTime Dateachat)
        {
            if ((Productid == null) || (ClientId == null))
            {
                return NotFound();
            }
            Facture facture = fctsrv.GetMany()
                .FirstOrDefault(m => m.ProductFk == Productid && m.ClientFk == ClientId && m.DateAchat == Dateachat); 
            if (facture == null)
            {
                return NotFound();
            }
            return View(facture);
        }

        // POST: FactureController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int Productid, int ClientId, DateTime Dateachat)
        {
            try
            {
                Facture facture = fctsrv.GetMany()
                .FirstOrDefault(m => m.ProductFk == Productid && m.ClientFk == ClientId && m.DateAchat == Dateachat);
               
                fctsrv.Delete(facture);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Web/Controllers/ProductController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using GP.Data;
using GP.Domain.Entities;
//
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;
using GP.Service;
using GP.Web.Models;
//
using Microsoft.AspNetCore.Hosting;
using System.IO;

namespace GP.Web.Controllers
{
    public class ProductController : Controller
    {
        // GET: ProductController

        private readonly IWebHostEnvironment hostEnvironment;
        private readonly IProductService productService;
        private readonly ICategoryService categoryService;

        public ProductController(IProductService _prdsrv, ICategoryService _catsrv, IWebHostEnvironment _hostEnvironment)
        {
            productService = _prdsrv;
            categoryService = _catsrv;
            hostEnvironment = _hostEnvironment;
        }

        public ActionResult Index2()
        {
            var list = productService.GetMany();
            return View(list);
        }
        public ActionResult Index(string filtre)
        {
            var listproduct = productService.GetMany();

            if (!String.IsNullOrEmpty(filtre))
            {
                listproduct = productService.GetProductByName(filtre);
            }

            List<ProductModel> listproductmodel = new List<ProductModel>();

            foreach (var product in listproduct)
            {
                var productmodel = new ProductModel(product);
                productmodel.NbreClient = productService.GetClientNbre(product.ProductId);
                listproductmodel.Add(productmodel);
            }

            return View(listproductmodel);
        }

        public ActionResult _Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var product = productService.GetMany()
                .FirstOrDefault(m => m.ProductId == id);

            if (product == null)
            {
                return NotFound();
            }
            return PartialView(product);

        }
        // GET: ProductController/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = productService.GetMany()
                .FirstOrDefault(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: ProductController/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(categoryService.GetMany(), "CategoryId", "Name");
            return View();
        }

        // POST: ProductController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Product p, IFormFile file )
        {
            try
            {
                string wwwRootPath = hostEnvironment.WebRootPath;
                string fileName = Path.GetFileNameWithoutExtension(file.FileName);
                string extension = Path.GetExtension(file.FileName);
                fileName = fileName + DateTime.Now.ToString("yymmssfff") + extension;
                p.ImageName = fileName;
                string path = Path.Combine(wwwRootPath + "/Upload/", fileName);
                using (var fileStream = new FileStream(path, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
                productService.Add(p);
                productService.Commit();
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ProductController/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = productService.GetById((int)id);
            if (product == null)
            {
                return NotFound();
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetMany(), "CategoryId", "Name", product.CategoryId);
            return View(product);
        }

        // POST: ProductController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Product prd)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    productService.Update(prd);
                    productService.Commit();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(prd.ProductId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewBag.CategoryId = new SelectList(categoryService.GetMany(), "CategoryId", "Name", prd.CategoryId);
            return View(prd);
        }

        // GET: ProductController/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = productService.GetMany()
                .FirstOrDefault(m => m.ProductId == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // POST: ProductController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id)
        {
            var product = productService.GetById(id);
            productService.Delete(product);
            productService.Commit();
            return RedirectToAction(nameof(Index));
        }

        private bool ProductExists(int id)
        {
            return productService.GetMany().Any(e => e.ProductId == id);
        }
    }
}

Web/Views/Product/Create.cshtml
@model GP.Domain.Entities.Product
@using GP.Domain.Entities;

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateProd" class="control-label"></label>
                <input asp-for="DateProd" class="form-control" />
                <span asp-validation-for="DateProd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageName" class="control-label"></label>
                @*<input asp-for="ImageName" class="form-control" />*@
                <input name="file" type="file" />
                <span asp-validation-for="ImageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
            </div>
            <div class="form-group">
                <label asp-for="PType" class="control-label"></label>
                <select asp-for="PType" class="form-control" asp-items="Html.GetEnumSelectList<PackagingType>()"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Product/Delete.cshtml
@model GP.Domain.Entities.Product

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateProd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateProd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MyCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MyCategory.Name)
        </dd class>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Web/Views/Product/Details.cshtml
@model GP.Domain.Entities.Product

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateProd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateProd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ImageName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MyCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MyCategory.Name)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Web/Views/Product/Edit.cshtml
@model GP.Domain.Entities.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <textarea asp-for="Description" class="form-control"></textarea>
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Quantity" class="control-label"></label>
                <input asp-for="Quantity" class="form-control" />
                <span asp-validation-for="Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DateProd" class="control-label"></label>
                <input asp-for="DateProd" class="form-control" />
                <span asp-validation-for="DateProd" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ImageName" class="control-label"></label>
                <input asp-for="ImageName" class="form-control" />
                <span asp-validation-for="ImageName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoryId" class="control-label"></label>
                <select asp-for="CategoryId" class="form-control" asp-items="ViewBag.CategoryId"></select>
                <span asp-validation-for="CategoryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Web/Views/Product/Index.cshtml
@model IEnumerable<GP.Web.Models.ProductModel >

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<form asp-action="Index">
    
    <table>
        <tr>
            <td>
                <div>
                    Recherche par Nom:   <input type="text" name="filtre"/>
                </div>
            </td>
            <td> <input type="submit" value="Rechercher" id="submit" /> </td>
        </tr>
    </table>
    
</form>
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Price)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Quantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.DateProd)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ImageName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Category)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.PType)
                </th>
                <th>
                    @Html.DisplayName("Nbre de Client")
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Price)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DateProd)
                </td>
                <td>
                    @*@Html.DisplayFor(modelItem => item.ImageName)*@
                    <img src="~/Upload/@item.ImageName" height="50" width="50" alt="Image" />
                </td>

                <td>
                    @Html.DisplayFor(modelItem => item.Category.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.PType)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.NbreClient)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ProductId">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ProductId">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ProductId">Delete</a>
                </td>
            </tr>
            }
        </tbody>
    </table>

Web/Views/Product/Index2.cshtml
@model IEnumerable<GP.Domain.Entities.Product>
@{
    ViewBag.Title = "Index2";
}

@foreach (var item in Model)
{
   
    <partial name="_Details"  model="item"/>
}

Web/Views/Product/_Details.cshtml
@model GP.Domain.Entities.Product

@{
    ViewData["Title"] = "_Details";
}


<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Description)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Description)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Quantity)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Quantity)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DateProd)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DateProd)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ImageName)
        </dt>
        <dd class="col-sm-10">
            @*@Html.DisplayFor(model => model.ImageName)*@
            <img src="@Url.Content("~/Upload/"+Model.ImageName)" height="50" width="50" alt="Image" />
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MyCategory)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MyCategory.Name)
        </dd>
    </dl>
</div>
<div>
    @*<a asp-action="Edit" asp-route-id="@Model.ProductId">Edit</a> |*@
    <a asp-controller="Facture" asp-action="Index">Back to List</a>
</div>